[tee]
tee_host = "http://127.0.0.1:8080"
basic_token = "eGF4rxS4PMGK3YZ"

[icp]
api_host = "https://icp-api.io"
cose_namespace = "anda"
cose_canister = "53cyg-yyaaa-aaaap-ahpua-cai"
object_store_canister = "6at64-oyaaa-aaaap-anvza-cai"
token_ledgers = []

[llm]
deepseek_api_key = ""
cohere_api_key = ""
cohere_embedding_model = ""
openai_api_key = ""
openai_embedding_model = ""
openai_completion_model = ""

[x]
username = ""
password = ""
email = ""
two_factor_auth = ""
cookie_string = ""

[google]
api_key = ""
search_engine_id = ""
