[log]
# Log level: "trace", "debug", "info", "warn", "error"
level = "debug"

[server]
# The address to bind to.
port = 8042

[character]
path = "./Character.toml"

[tee]
tee_host = "http://127.0.0.1:8080"
basic_token = ""

[icp]
api_host = "http://localhost:4943"
cose_namespace = "_"
cose_canister = "53cyg-yyaaa-aaaap-ahpua-cai"
object_store_canister = "6at64-oyaaa-aaaap-anvza-cai"
token_ledgers = []

[llm]
deepseek_api_key = ""
cohere_api_key = ""
cohere_embedding_model = "embed-multilingual-v3.0"
openai_api_key = ""
openai_embedding_model = ""
openai_completion_model = ""

[x]
username = ""
password = ""
email = ""
two_factor_auth = ""
cookie_string = ""

[google]
api_key = ""
search_engine_id = ""
